//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRIVER_ST10090631
    {
        public string DriverId { get; set; }
        public string DriverName { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public int Mobile { get; set; }
    }
}
