//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class POE_PART2_Ride_You_Rent_ST10090631Entities : DbContext
    {
        public POE_PART2_Ride_You_Rent_ST10090631Entities()
            : base("name=POE_PART2_Ride_You_Rent_ST10090631Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAR_ST10090631> CAR_ST10090631 { get; set; }
        public virtual DbSet<DRIVER_ST10090631> DRIVER_ST10090631 { get; set; }
        public virtual DbSet<INSPECTOR_ST10090631> INSPECTOR_ST10090631 { get; set; }
        public virtual DbSet<RENTAL_ST10090631> RENTAL_ST10090631 { get; set; }
        public virtual DbSet<RETURN_ST10090631> RETURN_ST10090631 { get; set; }
    }
}
