//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RENTAL_ST10090631
    {
        public string RentalId { get; set; }
        public string DriverId { get; set; }
        public string CarNo { get; set; }
        public string InspectorId { get; set; }
        public string RentalFee { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
    }
}
